on:
  schedules:
    - cron: '*/10 * * * *'
name: Update gist with WakaTime stats
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: update-gist
        uses: matchai/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 19412b507fe9b537e35ca7e07b253573
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
